### ISSUE TITLE
内核修改部分可以单独提出来吗，麒麟710，emui9.0，内核4.9.148试过很多次不行

### ISSUE THREAD

**Issue by wutaijieing** [Coconutat/android_kernel_huawei_vtr_emui8_KernelSU#1]

**Comment by Coconutat** [comment]
4.9以上华为魔改太多了，SELinux部分改的面目全非。ebitmap改了很多，KernelSU的SELinux 的sepolicy根本没法和华为魔改的policydb兼容。就比如正常的里面有type_attr_map_array，华为的是type_attr_map，而且正常的定义是struct flex_array *type_attr_map_array ,华为的是struct ebitmap *type_attr_map。声明定义都不同。只能自己魔改KernelSU的代码适应华为的代码。

**Comment by wutaijieing** [comment]
确实，你遇到的这些坑，我都踩过，主要是后面还是不行，能勾选，但是不生效
这是我以前作的一部分兼容补丁https://github.com/wutaijieing/android_kernel_Glk_kirin710/commits/main
关于ebitmap部分如果提示too many或者too little则需要在后面删除或加入,0

而且我用的是官方0修改的代码，我的这个cpu型号，网上基本没有公开的修改，所以应该还是缺失了不少补丁，应该是关于检测su/root部分的，所以才会不生效

我看到你已经成功了，所以想看看都改了哪一部分，还有kernelSU这部分的修改也想研究下， 你的这个库貌似是个本地的软连接，方便的话也传上来看看，万分感谢

**Comment by Coconutat** [comment]
> 

我今天试了下，9.0成功了.你可以在这里看看：[[android_kernel_huawei_vtr_emui9_KernelSU](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU)](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU）

**Comment by Coconutat** [comment]
> 确实，你遇到的这些坑，我都踩过，主要是后面还是不行，能勾选，但是不生效
> 这是我以前作的一部分兼容补丁https://github.com/wutaijieing/android_kernel_Glk_kirin710/commits/main
> 关于ebitmap部分如果提示too many或者too little则需要在后面删除或加入,0
> 
> 而且我用的是官方0修改的代码，我的这个cpu型号，网上基本没有公开的修改，所以应该还是缺失了不少补丁，应该是关于检测su/root部分的，所以才会不生效
> 
> 我看到你已经成功了，所以想看看都改了哪一部分，还有kernelSU这部分的修改也想研究下， 你的这个库貌似是个本地的软连接，方便的话也传上来看看，万分感谢


我今天试了下，9.0成功了.你可以在这里看看，这是我我编译9.0版本的内核代码：[android_kernel_huawei_vtr_emui9_KernelSU](https://github.com/Coconutat/android_kernel_huawei_vtr_emui9_KernelSU)，另外我发现华为的SELinux代码是移植自5.x版本的内核。8.0内核的KernelSU代码我也上传了。
